### ISSUE TITLE
Connector board

### ISSUE THREAD

**Issue by gtnz** [koendv/xy-stage#1]
Hello. 
Sorry, I don’t know where on github they ask questions, so I open issue.

Where can I get a connector board like in your project?

**Comment by koendv** [comment]
Thank you for your interest. This is a good question.

The board I use I soldered myself, by hand. If you wish to, I can send it to you for 15 EUR + what the post office charges me to send a small packet.

Soldering by hand becomes unpractical, even for small numbers. There are companies like jlcpcb, seeedstudio, elecrow that do pcb assembly for you, but then you have not one board, but 5.

**Comment by koendv** [comment]
I added documentation how I ordered the pcb and components, see https://github.com/koendv/xy-stage#connector-board
HTH

**Comment by gtnz** [comment]
Thank you very much
